### ISSUE TITLE
Does not seem to work on Windows 8.1

### ISSUE THREAD

**Issue by CaledoniaProject** [zodiacon/DllInjectionWithThreadContext#1]
The demo project fails on Windows 8.1, as result the injected process get stuck and the injector receives error `ERROR_INVALID_PARAMETER (87)`

Can you verify that?

**Comment by zodiacon** [comment]
I didn't test in Windows 8.1...
32 bit or 64 bit?

**Comment by CaledoniaProject** [comment]
64bit :-P

**Comment by CaledoniaProject** [comment]
I'll test it on more VMs and get back soon, Windows 7 x86 & x64

**Comment by friendWell** [comment]
您好，up主，我在win10 64位上运行您的程序，运行成功，注入的explorer.exe。但是没有反应，请问能解答一下吗，还有，32位的时候，GetThreadContext会报错，返回值为87。
期待您的回复

**Comment by friendWell** [comment]
oh，I'm sorry，I treat you as Chinese.
I tried it in Windows 10 64bit,it work successfully,and I injected in explorer.exe,the result is not whta I wanted,the Dll file doesn't work.
And I tried it in Windows 10 32 bit ,the function GetThreadContext() will return -1,GetLastError is 87.
Wish to get your reply!

**Comment by zodiacon** [comment]
What do you mean the DLL file doesn't work? If it's injected, then its DllMain is called; that's it.
Sorry, I don't have a readily available 32 bit system to check this, but error 87 is invalid argument. You should debug and check the thread handle that you get back.

**Comment by friendWell** [comment]
I finished it in 64bit,so it doesn't matter.The project works well,doesn't have a problem,but the DLL file seems to be that I don't inject in exe.So I don't know what's the matter.

**Comment by zodiacon** [comment]
Did you check with Process Explorer to see if the DLL was injected?
Other than that, I can't help without full source code.

**Comment by friendWell** [comment]
Thank you,I use Process Explorer to search the DLL file,I find it doesn't inject in,finally I know my file name is wrong,it's a silly mistake.But I want to know how to uninstall the DLL file,can you describe to me?

**Comment by zodiacon** [comment]
You can use FreeLibrary from within the target process, or you can inject in the same way a call to FreeLibrary.

**Comment by friendWell** [comment]
> 
> 
> You can use FreeLibrary from within the target process, or you can inject in the same way a call to FreeLibrary.

Oh,thank you ,sorry to bother you

**Comment by zodiacon** [comment]
No bother!
